// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qqpcprqnglvbtmtiptyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcGNwcnFuZ2x2YnRtdGlwdHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MjkyODksImV4cCI6MjA3OTQwNTI4OX0.GmtLUWLI_kl3VJxIuOdG1Jq8Bg01EiO1nEBnaQat0Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);